import * as THREE from "three";
import {
  barycentric,
  traceSurfacePath,
  type SurfaceStart,
  type TracedPath,
} from "./path-tracer";
import type {
  RoutePreset,
  RoutePresetId,
  WorldData,
  WorldMetadata,
} from "./world-data";

const INVALID_INDEX = 0xffffffff;
const DEFAULT_ROUTE: RoutePresetId = "ridge-crossing";

const ROUTE_COLORS: Record<RoutePresetId, number> = {
  "ridge-crossing": 0xffbd62,
  "saddle-pass": 0x78d5c6,
  "basin-rim": 0xc9afff,
};

const ACT_CAPTIONS = [
  "A closed, asymmetric surface generated by the C++ engine.",
  "The ambient chord leaves the surface and cannot be walked.",
  "Dijkstra follows mesh edges and inherits their directional bias.",
  "Choose a real starting point authored around a visible surface feature.",
  "Six exported diffusion states spread from one shared beacon.",
  "Depth-tested face arrows and a lifted route follow the reconstructed field.",
  "Contours show level sets of one Heat Method distance field.",
  "A restrained x-ray overlay keeps three fallback-free Heat paths readable.",
  "The C++ engine exports geometry, sparse-solve fields, and route diagnostics.",
  "A surface path recovered from heat.",
] as const;

interface SceneOptions {
  reducedMotion: boolean;
  onRouteSelected?: (preset: RoutePreset) => void;
}

type RouteVisual = {
  preset: RoutePreset;
  start: SurfaceStart;
  startNormal: THREE.Vector3;
  ambientLine: THREE.Line;
  dijkstraLine: THREE.Line;
  heatPath: THREE.Mesh;
  traced: TracedPath;
};

function vertexVector(
  data: WorldData | Float32Array,
  index: number,
  target = new THREE.Vector3(),
): THREE.Vector3 {
  return target.fromArray(
    data instanceof Float32Array ? data : data.positions,
    3 * index,
  );
}

function triangleVertices(
  data: WorldData,
  face: number,
): [THREE.Vector3, THREE.Vector3, THREE.Vector3] {
  return [
    vertexVector(data, data.indices[3 * face]!),
    vertexVector(data, data.indices[3 * face + 1]!),
    vertexVector(data, data.indices[3 * face + 2]!),
  ];
}

function interpolateSurfaceStart(
  data: WorldData,
  preset: RoutePreset,
): SurfaceStart {
  const point = new THREE.Vector3();
  for (let local = 0; local < 3; local += 1) {
    point.addScaledVector(
      vertexVector(data, data.indices[3 * preset.startFace + local]!),
      preset.startBarycentric[local]!,
    );
  }
  return { face: preset.startFace, point };
}

function interpolatedNormal(
  data: WorldData,
  face: number,
  point: THREE.Vector3,
): THREE.Vector3 {
  const vertices = triangleVertices(data, face);
  const weights = barycentric(point, ...vertices);
  const normal = new THREE.Vector3();
  for (let local = 0; local < 3; local += 1) {
    normal.addScaledVector(
      vertexVector(data.normals, data.indices[3 * face + local]!),
      weights[local]!,
    );
  }
  return normal.normalize();
}

function nearestVertexNormal(
  data: WorldData,
  point: THREE.Vector3,
): THREE.Vector3 {
  let best = 0;
  let bestSquaredDistance = Number.POSITIVE_INFINITY;
  const candidate = new THREE.Vector3();
  for (let vertex = 0; vertex < data.vertexCount; vertex += 1) {
    candidate.fromArray(data.positions, 3 * vertex);
    const squaredDistance = candidate.distanceToSquared(point);
    if (squaredDistance < bestSquaredDistance) {
      best = vertex;
      bestSquaredDistance = squaredDistance;
    }
  }
  return vertexVector(data.normals, best).normalize();
}

function liftedTracePoints(
  data: WorldData,
  traced: TracedPath,
  offset: number,
): THREE.Vector3[] {
  return traced.points.map((point, index) => {
    const face = traced.faces[index] ?? -1;
    const normal =
      face >= 0
        ? interpolatedNormal(data, face, point)
        : nearestVertexNormal(data, point);
    return point.clone().addScaledVector(normal, offset);
  });
}

function makeMarker(color: number, radius: number): THREE.Group {
  const group = new THREE.Group();
  const core = new THREE.Mesh(
    new THREE.SphereGeometry(radius, 18, 12),
    new THREE.MeshStandardMaterial({
      color,
      emissive: color,
      emissiveIntensity: 2.1,
      roughness: 0.34,
    }),
  );
  const ring = new THREE.Mesh(
    new THREE.TorusGeometry(radius * 1.9, radius * 0.07, 8, 36),
    new THREE.MeshBasicMaterial({ color, transparent: true, opacity: 0.65 }),
  );
  ring.rotation.x = Math.PI / 2;
  group.add(core, ring);
  return group;
}

function placeOnSurface(
  marker: THREE.Object3D,
  point: THREE.Vector3,
  normal: THREE.Vector3,
  offset: number,
): void {
  marker.position.copy(point).addScaledVector(normal, offset);
  marker.quaternion.setFromUnitVectors(
    new THREE.Vector3(0, 1, 0),
    normal.clone().normalize(),
  );
}

function makePathTube(
  points: readonly THREE.Vector3[],
  radius: number,
  color: number,
): THREE.Mesh {
  if (points.length < 2) throw new Error("A route needs at least two points");
  const curve = new THREE.CurvePath<THREE.Vector3>();
  for (let index = 0; index + 1 < points.length; index += 1) {
    curve.add(
      new THREE.LineCurve3(points[index]!.clone(), points[index + 1]!.clone()),
    );
  }
  return new THREE.Mesh(
    new THREE.TubeGeometry(
      curve,
      Math.max(72, Math.min(760, points.length * 4)),
      radius,
      6,
      false,
    ),
    new THREE.MeshBasicMaterial({
      color,
      toneMapped: false,
      transparent: true,
      opacity: 1,
      depthTest: true,
      depthWrite: false,
    }),
  );
}

function disposeObject(object: THREE.Object3D): void {
  object.traverse((child) => {
    if (child instanceof THREE.Mesh || child instanceof THREE.Line) {
      child.geometry.dispose();
      const materials = Array.isArray(child.material)
        ? child.material
        : [child.material];
      materials.forEach((material) => material.dispose());
    }
  });
}

export class WorldScene {
  private readonly data: WorldData;
  private readonly metadata: WorldMetadata;
  private readonly canvas: HTMLCanvasElement;
  private readonly reducedMotion: boolean;
  private readonly onRouteSelected?: (preset: RoutePreset) => void;
  private readonly scene = new THREE.Scene();
  private readonly camera = new THREE.PerspectiveCamera(36, 1, 0.01, 100);
  private readonly renderer: THREE.WebGLRenderer;
  private readonly world = new THREE.Group();
  private readonly geometry = new THREE.BufferGeometry();
  private readonly colors: Float32Array;
  private readonly baseColors: Float32Array;
  private readonly distanceColors: Float32Array;
  private readonly contourColors: Float32Array;
  private readonly colorAttribute: THREE.BufferAttribute;
  private readonly material: THREE.MeshStandardMaterial;
  private readonly mesh: THREE.Mesh;
  private readonly wireframe: THREE.Mesh;
  private readonly atmosphere: THREE.Mesh;
  private readonly beacon: THREE.Group;
  private readonly explorer: THREE.Group;
  private readonly gradientLines: THREE.LineSegments;
  private readonly routeVisuals = new Map<RoutePresetId, RouteVisual>();
  private readonly resizeObserver: ResizeObserver;
  private readonly cameraPositionTarget = new THREE.Vector3();
  private readonly cameraLookTarget = new THREE.Vector3();
  private readonly worldCenter = new THREE.Vector3();
  private worldRotationXTarget = 0;
  private worldRotationYTarget = 0;
  private readonly palette = new Float32Array(256 * 3);
  private selectedRouteId: RoutePresetId = DEFAULT_ROUTE;
  private comparisonVisible = false;
  private activeAct = 0;
  private heatStarted = false;
  private heatStartTime = 0;
  private routeReplayStart = 0;
  private routeReplayRevision = 0;
  private actStartTime = performance.now();
  private animationFrame = 0;
  private disposed = false;

  constructor(
    canvas: HTMLCanvasElement,
    data: WorldData,
    metadata: WorldMetadata,
    options: SceneOptions,
  ) {
    this.canvas = canvas;
    this.data = data;
    this.metadata = metadata;
    this.reducedMotion = options.reducedMotion;
    this.onRouteSelected = options.onRouteSelected;
    this.renderer = new THREE.WebGLRenderer({
      canvas,
      antialias: true,
      alpha: true,
      powerPreference: "high-performance",
    });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.75));
    this.renderer.outputColorSpace = THREE.SRGBColorSpace;
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.03;
    this.scene.fog = new THREE.FogExp2(0x000000, 0.035);

    this.geometry.setAttribute(
      "position",
      new THREE.BufferAttribute(data.positions, 3),
    );
    this.geometry.setAttribute(
      "normal",
      new THREE.BufferAttribute(data.normals, 3),
    );
    this.geometry.setIndex(new THREE.BufferAttribute(data.indices, 1));
    this.geometry.computeBoundingSphere();
    if (this.geometry.boundingSphere) {
      this.worldCenter.copy(this.geometry.boundingSphere.center);
    }
    this.baseColors = this.buildBaseColors();
    this.distanceColors = this.buildDistanceColors(false);
    this.contourColors = this.buildDistanceColors(true);
    this.colors = this.baseColors.slice();
    this.colorAttribute = new THREE.BufferAttribute(this.colors, 3);
    this.geometry.setAttribute("color", this.colorAttribute);

    this.material = new THREE.MeshStandardMaterial({
      vertexColors: true,
      roughness: 0.77,
      metalness: 0.015,
    });
    this.mesh = new THREE.Mesh(this.geometry, this.material);
    this.mesh.name = "computed-curved-world";
    this.wireframe = new THREE.Mesh(
      this.geometry,
      new THREE.MeshBasicMaterial({
        color: 0xa6c9c2,
        wireframe: true,
        transparent: true,
        opacity: 0,
        depthWrite: false,
      }),
    );
    this.wireframe.scale.setScalar(1.0012);
    this.atmosphere = new THREE.Mesh(
      this.geometry,
      new THREE.MeshBasicMaterial({
        color: 0x65c8b6,
        side: THREE.BackSide,
        transparent: true,
        opacity: 0.035,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
      }),
    );
    this.atmosphere.scale.setScalar(1.045);
    this.world.add(this.mesh, this.wireframe, this.atmosphere);

    const sourcePoint = vertexVector(data, data.sourceVertex);
    const sourceNormal = vertexVector(
      data.normals,
      data.sourceVertex,
    ).normalize();
    this.beacon = makeMarker(0xffc66d, 0.027);
    placeOnSurface(this.beacon, sourcePoint, sourceNormal, 0.035);
    const beaconLight = new THREE.PointLight(0xffb454, 1.55, 0.78, 1.8);
    beaconLight.position.set(0, 0.04, 0);
    this.beacon.add(beaconLight);
    this.world.add(this.beacon);

    this.explorer = makeMarker(0xf5f7f6, 0.022);
    this.world.add(this.explorer);

    this.gradientLines = this.createGradientLines();
    this.gradientLines.visible = false;
    this.world.add(this.gradientLines);
    this.buildPalette();
    this.buildRouteVisuals();

    this.world.rotation.set(0, 0, 0.02);
    this.scene.add(this.world);
    this.scene.add(new THREE.HemisphereLight(0xdcebe7, 0x050606, 1.35));
    const key = new THREE.DirectionalLight(0xffead0, 2.0);
    key.position.set(3.5, 3.2, 4.8);
    this.scene.add(key);
    const rim = new THREE.DirectionalLight(0x65d9c5, 0.9);
    rim.position.set(-3.2, 0.5, -2.5);
    this.scene.add(rim);

    this.canvas.dataset.act = "0";
    this.canvas.dataset.activeRoute = DEFAULT_ROUTE;
    this.canvas.dataset.comparison = "false";
    this.canvas.dataset.heatMode = "idle";
    this.positionExplorer();
    this.updateCameraTargets();
    this.world.rotation.x = this.worldRotationXTarget;
    this.world.rotation.y = this.worldRotationYTarget;
    this.camera.position.copy(this.cameraPositionTarget);
    this.camera.lookAt(this.cameraLookTarget);
    this.applyVisualState();

    this.canvas.addEventListener("keydown", this.handleKeyDown);
    this.resizeObserver = new ResizeObserver(() => this.resize());
    this.resizeObserver.observe(this.canvas);
    this.resize();
    this.animationFrame = requestAnimationFrame(this.render);
  }

  get caption(): string {
    if (this.comparisonVisible) return ACT_CAPTIONS[7];
    return ACT_CAPTIONS[this.activeAct] ?? ACT_CAPTIONS[0];
  }

  get selectedPreset(): RoutePreset {
    return this.routeVisuals.get(this.selectedRouteId)!.preset;
  }

  selectRoute(routeId: RoutePresetId): void {
    const visual = this.routeVisuals.get(routeId);
    if (!visual) throw new Error(`Unknown route preset: ${routeId}`);
    this.selectedRouteId = routeId;
    this.comparisonVisible = false;
    this.canvas.dataset.activeRoute = routeId;
    this.canvas.dataset.comparison = "false";
    this.positionExplorer();
    this.updateCameraTargets();
    this.applyVisualState();
    this.onRouteSelected?.(visual.preset);
  }

  showRouteComparison(): void {
    this.comparisonVisible = true;
    this.canvas.dataset.comparison = "true";
    this.updateCameraTargets();
    this.applyVisualState();
  }

  hideRouteComparison(): void {
    this.comparisonVisible = false;
    this.canvas.dataset.comparison = "false";
    this.updateCameraTargets();
    this.applyVisualState();
  }

  replayRoute(): void {
    this.hideRouteComparison();
    this.routeReplayStart = performance.now();
    this.routeReplayRevision += 1;
    this.canvas.dataset.routeReplay = String(this.routeReplayRevision);
  }

  resetJourney(): void {
    this.heatStarted = false;
    this.canvas.dataset.heatMode = "idle";
    delete this.canvas.dataset.heatProgress;
    this.activeAct = 0;
    this.canvas.dataset.act = "0";
    this.applyColors(this.baseColors);
    this.selectRoute(DEFAULT_ROUTE);
    this.camera.position.copy(this.cameraPositionTarget);
  }

  setAct(act: number): void {
    const next = Math.max(0, Math.min(9, act));
    if (next === this.activeAct) return;
    this.activeAct = next;
    this.canvas.dataset.act = String(next);
    this.actStartTime = performance.now();
    if (next === 7) this.showRouteComparison();
    else if (this.comparisonVisible) this.hideRouteComparison();

    const wireMaterial = this.wireframe.material as THREE.MeshBasicMaterial;
    wireMaterial.opacity = next === 2 ? 0.22 : next === 8 ? 0.16 : 0;
    this.wireframe.visible = wireMaterial.opacity > 0;
    this.gradientLines.visible = next === 5;
    if ([0, 1, 2, 3, 8].includes(next)) this.applyColors(this.baseColors);
    if (next === 4 && !this.heatStarted)
      this.applyHeatFrame(Math.floor(this.data.heatFrameCount / 2));
    if ([5, 7, 9].includes(next)) this.applyColors(this.distanceColors);
    if (next === 6) this.applyColors(this.contourColors);
    this.updateCameraTargets();
    this.applyVisualState();
  }

  releaseHeat(): void {
    this.heatStarted = true;
    this.heatStartTime = performance.now();
    this.activeAct = 4;
    this.canvas.dataset.act = "4";
    this.canvas.dataset.heatMode = "animation";
    this.canvas.dataset.heatProgress = "0";
    this.hideRouteComparison();
    this.updateCameraTargets();
  }

  destroy(): void {
    if (this.disposed) return;
    this.disposed = true;
    cancelAnimationFrame(this.animationFrame);
    this.resizeObserver.disconnect();
    this.canvas.removeEventListener("keydown", this.handleKeyDown);
    for (const visual of this.routeVisuals.values()) {
      disposeObject(visual.ambientLine);
      disposeObject(visual.dijkstraLine);
      disposeObject(visual.heatPath);
    }
    this.routeVisuals.clear();
    this.gradientLines.geometry.dispose();
    (this.gradientLines.material as THREE.Material).dispose();
    disposeObject(this.beacon);
    disposeObject(this.explorer);
    this.geometry.dispose();
    this.material.dispose();
    (this.wireframe.material as THREE.Material).dispose();
    (this.atmosphere.material as THREE.Material).dispose();
    this.renderer.dispose();
  }

  private buildBaseColors(): Float32Array {
    const result = new Float32Array(this.data.vertexCount * 3);
    const radii = new Float32Array(this.data.vertexCount);
    let minimumRadius = Number.POSITIVE_INFINITY;
    let maximumRadius = Number.NEGATIVE_INFINITY;
    for (let vertex = 0; vertex < this.data.vertexCount; vertex += 1) {
      const radius = vertexVector(this.data.positions, vertex).length();
      radii[vertex] = radius;
      minimumRadius = Math.min(minimumRadius, radius);
      maximumRadius = Math.max(maximumRadius, radius);
    }
    const range = Math.max(maximumRadius - minimumRadius, 1e-9);
    const low = new THREE.Color(0x102b2e);
    const high = new THREE.Color(0x748076);
    for (let vertex = 0; vertex < this.data.vertexCount; vertex += 1) {
      const radial = (radii[vertex]! - minimumRadius) / range;
      const normalY = this.data.normals[3 * vertex + 1]!;
      const mix = THREE.MathUtils.clamp(
        0.1 + 0.72 * radial + 0.1 * normalY,
        0,
        1,
      );
      const color = low.clone().lerp(high, mix);
      result.set([color.r, color.g, color.b], 3 * vertex);
    }
    return result;
  }

  private buildDistanceColors(contours: boolean): Float32Array {
    const result = new Float32Array(this.data.vertexCount * 3);
    let maximum = 0;
    for (const value of this.data.distance) maximum = Math.max(maximum, value);
    const cold = new THREE.Color(0x153438);
    const middle = new THREE.Color(0x4d857b);
    const warm = new THREE.Color(0xf2b65f);
    for (let vertex = 0; vertex < this.data.vertexCount; vertex += 1) {
      const normalized = THREE.MathUtils.clamp(
        this.data.distance[vertex]! / Math.max(maximum, 1e-9),
        0,
        1,
      );
      let color =
        normalized < 0.56
          ? cold.clone().lerp(middle, normalized / 0.56)
          : middle.clone().lerp(warm, (normalized - 0.56) / 0.44);
      if (contours) {
        const band =
          0.72 +
          0.28 * Math.pow(Math.abs(Math.sin(normalized * Math.PI * 22)), 7);
        color = color.multiplyScalar(band);
      }
      result.set([color.r, color.g, color.b], 3 * vertex);
    }
    return result;
  }

  private buildPalette(): void {
    const cold = new THREE.Color(0x0f2c34);
    const ember = new THREE.Color(0xc9693d);
    const hot = new THREE.Color(0xffd88c);
    for (let index = 0; index < 256; index += 1) {
      const value = index / 255;
      const color =
        value < 0.72
          ? cold.clone().lerp(ember, Math.pow(value / 0.72, 2.2))
          : ember.clone().lerp(hot, (value - 0.72) / 0.28);
      this.palette.set([color.r, color.g, color.b], 3 * index);
    }
  }

  private applyColors(source: Float32Array): void {
    this.colors.set(source);
    this.colorAttribute.needsUpdate = true;
  }

  private applyHeatFrame(frameIndex: number): void {
    const frame = this.data.heatFrames[frameIndex];
    if (!frame) return;
    for (let vertex = 0; vertex < this.data.vertexCount; vertex += 1) {
      const paletteIndex = Math.min(
        255,
        Math.max(0, Math.round(frame[vertex]! / 257)),
      );
      this.colors[3 * vertex] = this.palette[3 * paletteIndex]!;
      this.colors[3 * vertex + 1] = this.palette[3 * paletteIndex + 1]!;
      this.colors[3 * vertex + 2] = this.palette[3 * paletteIndex + 2]!;
    }
    this.colorAttribute.needsUpdate = true;
  }

  private applyHeat(progress: number): void {
    const scaled =
      THREE.MathUtils.clamp(progress, 0, 1) * (this.data.heatFrameCount - 1);
    const first = Math.floor(scaled);
    const second = Math.min(first + 1, this.data.heatFrameCount - 1);
    const mix = scaled - first;
    const a = this.data.heatFrames[first]!;
    const b = this.data.heatFrames[second]!;
    for (let vertex = 0; vertex < this.data.vertexCount; vertex += 1) {
      const normalized =
        THREE.MathUtils.lerp(a[vertex]!, b[vertex]!, mix) / 65535;
      const paletteIndex = Math.min(
        255,
        Math.max(0, Math.round(normalized * 255)),
      );
      this.colors[3 * vertex] = this.palette[3 * paletteIndex]!;
      this.colors[3 * vertex + 1] = this.palette[3 * paletteIndex + 1]!;
      this.colors[3 * vertex + 2] = this.palette[3 * paletteIndex + 2]!;
    }
    this.colorAttribute.needsUpdate = true;
    this.canvas.dataset.heatProgress = THREE.MathUtils.clamp(
      progress,
      0,
      1,
    ).toFixed(3);
  }

  private createGradientLines(): THREE.LineSegments {
    const positions: number[] = [];
    this.data.gradientSamples.forEach((sample, sampleIndex) => {
      if (sampleIndex % 2 !== 0) return;
      const start = new THREE.Vector3(...sample.position);
      const direction = new THREE.Vector3(...sample.direction).normalize();
      const tip = start.clone().addScaledVector(direction, 0.052);
      const normal = new THREE.Vector3();
      for (let local = 0; local < 3; local += 1) {
        normal.add(
          vertexVector(
            this.data.normals,
            this.data.indices[3 * sample.face + local]!,
          ),
        );
      }
      normal.normalize();
      const side = new THREE.Vector3()
        .crossVectors(direction, normal)
        .normalize();
      const back = tip.clone().addScaledVector(direction, -0.013);
      positions.push(...start.toArray(), ...tip.toArray());
      positions.push(
        ...tip.toArray(),
        ...back.clone().addScaledVector(side, 0.0055).toArray(),
      );
      positions.push(
        ...tip.toArray(),
        ...back.clone().addScaledVector(side, -0.0055).toArray(),
      );
    });
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute(
      "position",
      new THREE.Float32BufferAttribute(positions, 3),
    );
    return new THREE.LineSegments(
      geometry,
      new THREE.LineBasicMaterial({
        color: 0xb5eee4,
        transparent: true,
        opacity: 0.7,
        depthTest: true,
        depthWrite: false,
      }),
    );
  }

  private buildRouteVisuals(): void {
    const source = vertexVector(this.data.positions, this.data.sourceVertex);
    for (const preset of this.metadata.routePresets) {
      const start = interpolateSurfaceStart(this.data, preset);
      const startNormal = interpolatedNormal(
        this.data,
        start.face,
        start.point,
      );
      const ambientLine = new THREE.Line(
        new THREE.BufferGeometry().setFromPoints([start.point, source]),
        new THREE.LineDashedMaterial({
          color: 0xd7a8ff,
          dashSize: 0.055,
          gapSize: 0.035,
          transparent: true,
          opacity: 0.9,
          depthTest: false,
          depthWrite: false,
        }),
      );
      ambientLine.computeLineDistances();

      const dijkstraPoints = [
        start.point.clone().addScaledVector(startNormal, 0.014),
      ];
      let current = preset.dijkstraStartVertex;
      for (let step = 0; step <= this.data.vertexCount; step += 1) {
        const point = vertexVector(this.data.positions, current);
        const normal = vertexVector(this.data.normals, current).normalize();
        dijkstraPoints.push(point.addScaledVector(normal, 0.014));
        if (current === this.data.sourceVertex) break;
        const next = this.data.dijkstraPredecessor[current]!;
        if (next === INVALID_INDEX || next === current)
          throw new Error(`Dijkstra route failed for ${preset.id}`);
        current = next;
      }
      const dijkstraLine = new THREE.Line(
        new THREE.BufferGeometry().setFromPoints(dijkstraPoints),
        new THREE.LineBasicMaterial({
          color: 0xe0b8ff,
          transparent: true,
          opacity: 1,
          depthTest: true,
          depthWrite: false,
        }),
      );

      const traced = traceSurfacePath(this.data, start);
      if (!traced.reachedSource)
        throw new Error(
          `Browser tracer failed for ${preset.id}: ${traced.termination}`,
        );
      const heatPath = makePathTube(
        liftedTracePoints(this.data, traced, 0.015),
        0.009,
        ROUTE_COLORS[preset.id],
      );
      this.routeVisuals.set(preset.id, {
        preset,
        start,
        startNormal,
        ambientLine,
        dijkstraLine,
        heatPath,
        traced,
      });
    }
  }

  private positionExplorer(): void {
    const visual = this.routeVisuals.get(this.selectedRouteId)!;
    placeOnSurface(
      this.explorer,
      visual.start.point,
      visual.startNormal,
      0.029,
    );
  }

  private updateCameraTargets(): void {
    const visual = this.routeVisuals.get(this.selectedRouteId)!;
    const source = vertexVector(this.data.positions, this.data.sourceVertex);
    const midpoint = visual.start.point.clone().add(source).multiplyScalar(0.5);

    // Derive framing from the authored surface starts. This turns the actual
    // ridge, saddle, or basin toward the viewer without unrelated camera
    // coordinates being duplicated in browser code.
    const framingDirection = new THREE.Vector3();
    if (this.comparisonVisible) {
      for (const route of this.routeVisuals.values()) {
        framingDirection.add(
          route.start.point.clone().sub(this.worldCenter).normalize(),
        );
      }
    } else {
      framingDirection.copy(visual.start.point).sub(this.worldCenter);
    }
    framingDirection.normalize();
    this.worldRotationYTarget = Math.atan2(
      -framingDirection.x,
      framingDirection.z,
    );
    const elevation = Math.atan2(
      framingDirection.y,
      Math.hypot(framingDirection.x, framingDirection.z),
    );
    this.worldRotationXTarget = THREE.MathUtils.clamp(
      elevation * 0.55,
      -0.65,
      0.65,
    );
    const framingRotation = new THREE.Euler(
      this.worldRotationXTarget,
      this.worldRotationYTarget,
      0,
      "XYZ",
    );
    const rotatedCenter = this.worldCenter.clone().applyEuler(framingRotation);
    const rotatedMidpoint = midpoint.applyEuler(framingRotation);
    this.cameraLookTarget
      .copy(rotatedCenter)
      .lerp(
        this.comparisonVisible ? rotatedCenter : rotatedMidpoint,
        this.comparisonVisible ? 0 : 0.12,
      );
    const mobile = window.matchMedia("(max-width: 760px)").matches;
    const distance = mobile ? 7.15 : this.activeAct === 2 ? 6.65 : 6.9;
    this.cameraPositionTarget
      .copy(this.cameraLookTarget)
      .add(new THREE.Vector3(0, 0, distance));
  }

  private applyVisualState(): void {
    for (const [id, visual] of this.routeVisuals) {
      visual.ambientLine.removeFromParent();
      visual.dijkstraLine.removeFromParent();
      visual.heatPath.removeFromParent();
      const heatMaterial = visual.heatPath.material as THREE.MeshBasicMaterial;
      heatMaterial.opacity = id === this.selectedRouteId ? 1 : 0.86;
      heatMaterial.depthTest = true;
      visual.heatPath.renderOrder = 0;
    }
    if (this.comparisonVisible) {
      for (const visual of this.routeVisuals.values()) {
        const heatMaterial = visual.heatPath
          .material as THREE.MeshBasicMaterial;
        heatMaterial.depthTest = false;
        heatMaterial.opacity = 0.9;
        visual.heatPath.renderOrder = 3;
        this.world.add(visual.heatPath);
      }
      return;
    }
    const active = this.routeVisuals.get(this.selectedRouteId)!;
    if (this.activeAct === 1) this.world.add(active.ambientLine);
    if (this.activeAct === 2) {
      active.dijkstraLine.geometry.setDrawRange(0, 1);
      this.world.add(active.dijkstraLine);
    }
    if (this.activeAct >= 3 && this.activeAct !== 4)
      this.world.add(active.heatPath);
    if (this.activeAct === 4 && this.heatStarted)
      this.world.add(active.heatPath);
  }

  private resize(): void {
    const rect = this.canvas.getBoundingClientRect();
    if (rect.width <= 0 || rect.height <= 0) return;
    this.renderer.setSize(rect.width, rect.height, false);
    this.camera.aspect = rect.width / rect.height;
    this.camera.updateProjectionMatrix();
    this.updateCameraTargets();
  }

  private readonly handleKeyDown = (event: KeyboardEvent): void => {
    if (event.key !== "Enter" && event.key !== " ") return;
    event.preventDefault();
    this.selectRoute(DEFAULT_ROUTE);
  };

  private readonly render = (time: number): void => {
    if (this.disposed) return;
    const ease = this.reducedMotion ? 1 : 0.045;
    this.camera.position.lerp(this.cameraPositionTarget, ease);
    const currentLook = new THREE.Vector3();
    this.camera.getWorldDirection(currentLook);
    const lookPoint = this.camera.position.clone().add(currentLook);
    lookPoint.lerp(this.cameraLookTarget, ease);
    this.camera.lookAt(lookPoint);
    if (!this.reducedMotion) {
      this.beacon.scale.setScalar(1 + 0.08 * Math.sin(time * 0.004));
      this.explorer.scale.setScalar(1 + 0.03 * Math.sin(time * 0.0032 + 1));
    }
    const rotationEase = this.reducedMotion ? 1 : 0.055;
    this.world.rotation.x = THREE.MathUtils.lerp(
      this.world.rotation.x,
      this.worldRotationXTarget,
      rotationEase,
    );
    this.world.rotation.y = THREE.MathUtils.lerp(
      this.world.rotation.y,
      this.worldRotationYTarget +
        (this.reducedMotion ? 0 : 0.018 * Math.sin(time * 0.00016)),
      rotationEase,
    );
    const selected = this.routeVisuals.get(this.selectedRouteId)!;
    if (this.activeAct === 2 && selected.dijkstraLine.parent) {
      const count =
        selected.dijkstraLine.geometry.getAttribute("position").count;
      const progress = this.reducedMotion
        ? 1
        : Math.min(1, (time - this.actStartTime) / 1700);
      selected.dijkstraLine.geometry.setDrawRange(
        0,
        Math.max(2, Math.floor(count * progress)),
      );
    }
    if (this.activeAct === 4 && this.heatStarted) {
      const duration = this.reducedMotion ? 1 : 4200;
      const progress = Math.min(1, (time - this.heatStartTime) / duration);
      this.applyHeat(progress);
    }
    if (this.routeReplayStart > 0 && selected.heatPath.parent) {
      const progress = this.reducedMotion
        ? 1
        : Math.min(1, (time - this.routeReplayStart) / 1200);
      (selected.heatPath.material as THREE.MeshBasicMaterial).opacity =
        0.2 + 0.8 * progress;
      if (progress >= 1) this.routeReplayStart = 0;
    }
    this.renderer.render(this.scene, this.camera);
    this.animationFrame = requestAnimationFrame(this.render);
  };
}
